import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CalendarDays, ChevronRight, Edit3, Loader2, Plus, Search, ShieldCheck, UserRound, X } from "lucide-react";
import { AuthGuard } from "@/components/auth-guard";
import { supabase } from "@/lib/supabase";
import type { AppRole } from "@/lib/auth";

export const Route = createFileRoute("/alunos")({ component: StudentsRoute });

type Student = {
  user_id: string; full_name: string; phone: string | null; birth_date: string | null; cpf: string | null;
  emergency_contact_name: string | null; emergency_contact_phone: string | null; status: "ACTIVE" | "INACTIVE" | "SUSPENDED"; enrollment_date: string; notes: string | null;
  belt: string; plan: string; payment: string;
};

const statusLabels = { ACTIVE: "Ativo", INACTIVE: "Inativo", SUSPENDED: "Suspenso" };

function StudentsRoute() { return <AuthGuard allowedRoles={["OWNER", "ADMIN", "TEACHER"]}><Students /></AuthGuard>; }

function Students() {
  const [students, setStudents] = useState<Student[]>([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState<"ALL" | Student["status"]>("ALL");
  const [selected, setSelected] = useState<Student | null>(null);
  const [editing, setEditing] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");

  const loadStudents = async () => {
    setLoading(true); setError("");
    const { data, error: dbError } = await supabase.from("student_profiles").select("user_id, birth_date, cpf, emergency_contact_name, emergency_contact_phone, status, enrollment_date, notes, profiles!inner(full_name, phone), student_graduations(belts(name, color), graduation_date), enrollments(plans(name, active)), invoices(status)").order("enrollment_date", { ascending: false });
    if (dbError) { setError(dbError.message); setLoading(false); return; }
    const mapped = (data ?? []).map((row: any) => {
      const graduation = [...(row.student_graduations ?? [])].sort((a: any, b: any) => String(b.graduation_date).localeCompare(String(a.graduation_date)))[0];
      const enrollment = (row.enrollments ?? []).find((e: any) => e.active) ?? row.enrollments?.[0];
      const invoices = row.invoices ?? [];
      const hasOverdue = invoices.some((i: any) => i.status === "OVERDUE");
      return { ...row, full_name: row.profiles?.full_name ?? "Sem nome", phone: row.profiles?.phone ?? null, belt: graduation?.belts?.name ?? "Sem graduação", plan: enrollment?.plans?.name ?? "Sem plano", payment: hasOverdue ? "Em atraso" : "Em dia" } as Student;
    });
    setStudents(mapped); setLoading(false);
  };

  useEffect(() => { loadStudents(); }, []);

  const filtered = useMemo(() => students.filter((s) => (status === "ALL" || s.status === status) && (`${s.full_name} ${s.cpf ?? ""} ${s.phone ?? ""}`.toLowerCase().includes(query.toLowerCase()))), [students, query, status]);

  return <div className="min-h-screen bg-ink text-foreground dashboard-atmosphere"><header className="sticky top-0 z-20 flex h-16 items-center border-b border-hairline bg-obsidian/90 px-4 backdrop-blur sm:px-6"><div><h1 className="text-[15px] font-semibold">Alunos</h1><p className="mt-1 font-mono text-[10px] uppercase tracking-[.15em] text-faint">Gestão de alunos</p></div><div className="ml-auto flex items-center gap-2"><button onClick={() => { setSelected({ user_id: "", full_name: "", phone: null, birth_date: null, cpf: null, emergency_contact_name: null, emergency_contact_phone: null, status: "ACTIVE", enrollment_date: new Date().toISOString().slice(0,10), notes: null, belt: "Sem graduação", plan: "Sem plano", payment: "Em dia" }); setEditing(true); }} className="flex h-10 items-center gap-2 rounded-xl bg-primary px-3.5 text-xs font-semibold text-primary-foreground hover:brightness-110"><Plus className="size-4"/><span className="hidden sm:inline">Novo aluno</span></button></div></header>
    <main className="mx-auto max-w-[1280px] px-4 py-5 sm:px-6 sm:py-7"><div className="mb-5 grid gap-3 sm:grid-cols-[1fr_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-faint"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por nome, CPF ou telefone..." className="h-11 w-full rounded-xl border border-hairline bg-panel pl-10 pr-3 text-sm outline-none focus:border-primary"/></div><select value={status} onChange={(e) => setStatus(e.target.value as any)} className="h-11 rounded-xl border border-hairline bg-panel px-3 text-sm outline-none focus:border-primary"><option value="ALL">Todos os status</option><option value="ACTIVE">Ativos</option><option value="INACTIVE">Inativos</option><option value="SUSPENDED">Suspensos</option></select></div>
      <div className="mb-4 flex items-center justify-between"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-faint">{filtered.length} aluno(s)</p>{error && <p className="text-xs text-red-300">Erro: {error}</p>}</div>
      {loading ? <div className="flex min-h-48 items-center justify-center"><Loader2 className="size-6 animate-spin text-primary"/></div> : filtered.length === 0 ? <div className="rounded-2xl border border-dashed border-hairline bg-panel/40 px-6 py-16 text-center"><UserRound className="mx-auto size-8 text-faint"/><p className="mt-3 font-medium">Nenhum aluno encontrado</p><p className="mt-1 text-sm text-faint">Ajuste a busca ou cadastre um novo aluno.</p></div> : <div className="overflow-hidden rounded-2xl border border-hairline bg-panel/50"><div className="hidden grid-cols-[1.6fr_.8fr_.9fr_.8fr_32px] gap-4 border-b border-hairline px-5 py-3 font-mono text-[9px] uppercase tracking-[.16em] text-faint md:grid"><span>Aluno</span><span>Graduação</span><span>Plano</span><span>Pagamento</span><span/></div>{filtered.map((student) => <button key={student.user_id} onClick={() => { setSelected(student); setEditing(false); }} className="grid w-full grid-cols-[1fr_28px] items-center gap-3 border-b border-hairline px-4 py-4 text-left last:border-0 hover:bg-white/[.025] md:grid-cols-[1.6fr_.8fr_.9fr_.8fr_32px] md:px-5"><div className="min-w-0"><p className="truncate text-sm font-medium">{student.full_name}</p><p className="mt-1 truncate text-[11px] text-faint">{student.phone || "Sem telefone"}<span className="mx-1.5">·</span><span className={student.status === "ACTIVE" ? "text-accent-soft" : "text-mist"}>{statusLabels[student.status]}</span></p></div><span className="hidden text-xs text-mist md:block">{student.belt}</span><span className="hidden text-xs text-mist md:block">{student.plan}</span><span className={student.payment === "Em dia" ? "hidden text-xs text-accent-soft md:block" : "hidden text-xs text-red-300 md:block"}>{student.payment}</span><ChevronRight className="size-4 text-faint"/></button>)}</div>}
    </main>
    {selected && !editing && <StudentDetail student={selected} onClose={() => setSelected(null)} onEdit={() => setEditing(true)} />}
    {selected && editing && <StudentForm student={selected} onClose={() => { setEditing(false); if (!selected.user_id) setSelected(null); }} onSaved={() => { setEditing(false); setSelected(null); loadStudents(); }} />}
  </div>;
}

function StudentDetail({ student, onClose, onEdit }: { student: Student; onClose: () => void; onEdit: () => void }) {
  const [tab, setTab] = useState("personal");
  return <div className="fixed inset-0 z-30 bg-black/60 backdrop-blur-sm"><aside className="absolute right-0 top-0 flex h-full w-full max-w-xl flex-col border-l border-hairline bg-obsidian shadow-2xl"><div className="flex h-16 items-center gap-3 border-b border-hairline px-5"><button onClick={onClose} className="rounded-lg p-2 text-faint hover:bg-panel hover:text-foreground"><ArrowLeft className="size-4"/></button><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{student.full_name}</p><p className="font-mono text-[9px] uppercase tracking-[.16em] text-faint">Perfil do aluno</p></div><button onClick={onEdit} className="flex items-center gap-2 rounded-lg border border-hairline bg-panel px-3 py-2 text-xs font-medium hover:border-primary"><Edit3 className="size-3.5"/>Editar</button></div><div className="border-b border-hairline px-5"><div className="flex gap-5 overflow-x-auto">{[["personal","Pessoal"],["graduations","Graduações"],["finance","Financeiro"],["attendance","Frequência"]].map(([id,label]) => <button key={id} onClick={() => setTab(id ?? "")} className={tab === id ? "border-b-2 border-primary py-3 text-xs font-semibold text-foreground" : "border-b-2 border-transparent py-3 text-xs text-faint hover:text-mist"}>{label}</button>)}</div></div><div className="flex-1 overflow-y-auto p-5">{tab === "personal" && <InfoGrid items={[["Status",statusLabels[student.status]],["Telefone",student.phone || "Não informado"],["CPF",student.cpf || "Não informado"],["Nascimento",student.birth_date || "Não informado"],["Matrícula",student.enrollment_date],["Contato de emergência",student.emergency_contact_name || "Não informado"],["Telefone emergência",student.emergency_contact_phone || "Não informado"]]} />}{tab === "graduations" && <div className="rounded-xl border border-hairline bg-panel p-4"><p className="text-sm font-medium">Graduação atual</p><p className="mt-2 text-lg font-semibold">{student.belt}</p><p className="mt-1 text-xs text-faint">Histórico completo será exibido conforme novas graduações forem registradas.</p></div>}{tab === "finance" && <InfoGrid items={[["Plano atual",student.plan],["Situação",student.payment],["Status",student.status === "ACTIVE" ? "Matrícula ativa" : statusLabels[student.status]]]} />}{tab === "attendance" && <div className="rounded-xl border border-hairline bg-panel p-4"><p className="text-sm font-medium">Frequência</p><p className="mt-2 text-xs text-faint">Os check-ins do aluno aparecerão aqui conforme as aulas forem registradas.</p></div>}</div></aside></div>;
}
function InfoGrid({ items }: { items: string[][] }) { return <div className="grid gap-3 sm:grid-cols-2">{items.map(([label,value]) => <div key={label} className="rounded-xl border border-hairline bg-panel/70 p-4"><p className="font-mono text-[9px] uppercase tracking-[.15em] text-faint">{label}</p><p className="mt-2 text-sm text-mist">{value}</p></div>)}</div>; }

function StudentForm({ student, onClose, onSaved }: { student: Student; onClose: () => void; onSaved: () => void }) {
  const isNew = !student.user_id;
  const [name, setName] = useState(student.full_name); const [phone, setPhone] = useState(student.phone ?? ""); const [birth, setBirth] = useState(student.birth_date ?? ""); const [cpf, setCpf] = useState(student.cpf ?? ""); const [emergencyName, setEmergencyName] = useState(student.emergency_contact_name ?? ""); const [emergencyPhone, setEmergencyPhone] = useState(student.emergency_contact_phone ?? ""); const [studentStatus, setStudentStatus] = useState(student.status); const [notes, setNotes] = useState(student.notes ?? ""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const save = async () => { setSaving(true); setError(""); try { if (isNew) { if (!email || password.length < 6) throw new Error("Informe um e-mail e uma senha com pelo menos 6 caracteres."); const { data, error: authError } = await supabase.auth.signUp({ email, password, options: { data: { full_name: name, phone } } }); if (authError) throw authError; if (!data.user) throw new Error("Não foi possível criar o usuário."); const { error: profileError } = await supabase.from("profiles").update({ full_name: name, phone }).eq("id", data.user.id); if (profileError) throw profileError; const { error: studentError } = await supabase.from("student_profiles").insert({ user_id: data.user.id, birth_date: birth || null, cpf: cpf || null, emergency_contact_name: emergencyName || null, emergency_contact_phone: emergencyPhone || null, status: studentStatus, notes: notes || null }); if (studentError) throw studentError; } else { const { error: profileError } = await supabase.from("profiles").update({ full_name: name, phone }).eq("id", student.user_id); if (profileError) throw profileError; const { error: studentError } = await supabase.from("student_profiles").update({ birth_date: birth || null, cpf: cpf || null, emergency_contact_name: emergencyName || null, emergency_contact_phone: emergencyPhone || null, status: studentStatus, notes: notes || null }).eq("user_id", student.user_id); if (studentError) throw studentError; } onSaved(); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível salvar."); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-40 grid place-items-center bg-black/70 p-4 backdrop-blur-sm"><section className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-hairline bg-obsidian shadow-2xl"><div className="flex items-center gap-3 border-b border-hairline px-5 py-4"><div className="grid size-9 place-items-center rounded-xl bg-primary/15 text-accent-soft"><UserRound className="size-4"/></div><div className="flex-1"><h2 className="text-sm font-semibold">{isNew ? "Cadastrar aluno" : "Editar aluno"}</h2><p className="mt-0.5 text-[11px] text-faint">Dados pessoais e acesso</p></div><button onClick={onClose} className="text-faint hover:text-foreground"><X className="size-4"/></button></div><div className="grid gap-4 p-5 sm:grid-cols-2"><Field label="Nome completo" value={name} onChange={setName} required/><Field label="Telefone" value={phone} onChange={setPhone}/>{isNew && <><Field label="E-mail de acesso" value={email} onChange={setEmail} type="email" required/><Field label="Senha inicial" value={password} onChange={setPassword} type="password" required/></>}<Field label="Data de nascimento" value={birth} onChange={setBirth} type="date"/><Field label="CPF" value={cpf} onChange={setCpf}/><Field label="Contato de emergência" value={emergencyName} onChange={setEmergencyName}/><Field label="Telefone de emergência" value={emergencyPhone} onChange={setEmergencyPhone}/><label className="block"><span className="mb-2 block text-[11px] font-medium text-mist">Status</span><select value={studentStatus} onChange={(e) => setStudentStatus(e.target.value as any)} className="h-11 w-full rounded-xl border border-hairline bg-panel px-3 text-sm outline-none focus:border-primary"><option value="ACTIVE">Ativo</option><option value="INACTIVE">Inativo</option><option value="SUSPENDED">Suspenso</option></select></label><label className="block sm:col-span-2"><span className="mb-2 block text-[11px] font-medium text-mist">Observações</span><textarea value={notes} onChange={(e) => setNotes(e.target.value)} rows={4} className="w-full rounded-xl border border-hairline bg-panel px-3 py-3 text-sm outline-none focus:border-primary" placeholder="Observações internas..."/></label></div>{error && <p className="mx-5 mb-4 rounded-xl border border-red-500/30 bg-red-500/10 px-3 py-2 text-xs text-red-300">{error}</p>}<div className="flex justify-end gap-2 border-t border-hairline p-5"><button onClick={onClose} className="rounded-xl border border-hairline px-4 py-2.5 text-xs font-medium text-mist hover:bg-panel">Cancelar</button><button disabled={saving} onClick={save} className="flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-semibold text-primary-foreground disabled:opacity-60">{saving && <Loader2 className="size-3.5 animate-spin"/>}Salvar aluno</button></div></section></div>;
}

function Field({ label, value, onChange, type = "text", required = false }: { label: string; value: string; onChange: (v: string) => void; type?: string; required?: boolean }) { return <label className="block"><span className="mb-2 block text-[11px] font-medium text-mist">{label}</span><input required={required} type={type} value={value} onChange={(e) => onChange(e.target.value)} className="h-11 w-full rounded-xl border border-hairline bg-panel px-3 text-sm outline-none focus:border-primary" /></label>; }
