/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as FrequenciaRouteImport } from './routes/frequencia'
import { Route as GraduacoesRouteImport } from './routes/graduacoes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MinhasAulasRouteImport } from './routes/minhas-aulas'
import { Route as RetencaoRouteImport } from './routes/retencao'
import { Route as TurmasRouteImport } from './routes/turmas'
import { Route as TvRouteImport } from './routes/tv'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const FrequenciaRoute = FrequenciaRouteImport.update({
  id: '/frequencia',
  path: '/frequencia',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduacoesRoute = GraduacoesRouteImport.update({
  id: '/graduacoes',
  path: '/graduacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasAulasRoute = MinhasAulasRouteImport.update({
  id: '/minhas-aulas',
  path: '/minhas-aulas',
  getParentRoute: () => rootRouteImport,
} as any)
const RetencaoRoute = RetencaoRouteImport.update({
  id: '/retencao',
  path: '/retencao',
  getParentRoute: () => rootRouteImport,
} as any)
const TurmasRoute = TurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/financeiro': typeof FinanceiroRoute
  '/frequencia': typeof FrequenciaRoute
  '/graduacoes': typeof GraduacoesRoute
  '/login': typeof LoginRoute
  '/minhas-aulas': typeof MinhasAulasRoute
  '/retencao': typeof RetencaoRoute
  '/turmas': typeof TurmasRoute
  '/tv': typeof TvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/financeiro': typeof FinanceiroRoute
  '/frequencia': typeof FrequenciaRoute
  '/graduacoes': typeof GraduacoesRoute
  '/login': typeof LoginRoute
  '/minhas-aulas': typeof MinhasAulasRoute
  '/retencao': typeof RetencaoRoute
  '/turmas': typeof TurmasRoute
  '/tv': typeof TvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/financeiro': typeof FinanceiroRoute
  '/frequencia': typeof FrequenciaRoute
  '/graduacoes': typeof GraduacoesRoute
  '/login': typeof LoginRoute
  '/minhas-aulas': typeof MinhasAulasRoute
  '/retencao': typeof RetencaoRoute
  '/turmas': typeof TurmasRoute
  '/tv': typeof TvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alunos'
    | '/financeiro'
    | '/frequencia'
    | '/graduacoes'
    | '/login'
    | '/minhas-aulas'
    | '/retencao'
    | '/turmas'
    | '/tv'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alunos'
    | '/financeiro'
    | '/frequencia'
    | '/graduacoes'
    | '/login'
    | '/minhas-aulas'
    | '/retencao'
    | '/turmas'
    | '/tv'
  id:
    | '__root__'
    | '/'
    | '/alunos'
    | '/financeiro'
    | '/frequencia'
    | '/graduacoes'
    | '/login'
    | '/minhas-aulas'
    | '/retencao'
    | '/turmas'
    | '/tv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunosRoute: typeof AlunosRoute
  FinanceiroRoute: typeof FinanceiroRoute
  FrequenciaRoute: typeof FrequenciaRoute
  GraduacoesRoute: typeof GraduacoesRoute
  LoginRoute: typeof LoginRoute
  MinhasAulasRoute: typeof MinhasAulasRoute
  RetencaoRoute: typeof RetencaoRoute
  TurmasRoute: typeof TurmasRoute
  TvRoute: typeof TvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frequencia': {
      id: '/frequencia'
      path: '/frequencia'
      fullPath: '/frequencia'
      preLoaderRoute: typeof FrequenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduacoes': {
      id: '/graduacoes'
      path: '/graduacoes'
      fullPath: '/graduacoes'
      preLoaderRoute: typeof GraduacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-aulas': {
      id: '/minhas-aulas'
      path: '/minhas-aulas'
      fullPath: '/minhas-aulas'
      preLoaderRoute: typeof MinhasAulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retencao': {
      id: '/retencao'
      path: '/retencao'
      fullPath: '/retencao'
      preLoaderRoute: typeof RetencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turmas': {
      id: '/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof TurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunosRoute: AlunosRoute,
  FinanceiroRoute: FinanceiroRoute,
  FrequenciaRoute: FrequenciaRoute,
  GraduacoesRoute: GraduacoesRoute,
  LoginRoute: LoginRoute,
  MinhasAulasRoute: MinhasAulasRoute,
  RetencaoRoute: RetencaoRoute,
  TurmasRoute: TurmasRoute,
  TvRoute: TvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
